#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog -f ../filelist/filelist.f 

