#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog -v ../dut/cnt_0_f.v ../tb/cnt_0_f_tb.v 

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.cnt_0_f_tb -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -radix hexadecimal cnt_0_f_tb/u_cnt_0_f/rst     
add wave -noupdate -format logic -radix hexadecimal cnt_0_f_tb/u_cnt_0_f/clk     
add wave -noupdate -format logic -radix hexadecimal cnt_0_f_tb/u_cnt_0_f/en     
add wave -noupdate -format logic -radix hexadecimal cnt_0_f_tb/u_cnt_0_f/cnt     
      
run 1us
