#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog -v ../dut/full_adder_tri.v ../tb/tb_full_adder_tri.v 

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.tb_full_adder_tri -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -radix hexadecimal tb_full_adder_tri/en     
add wave -noupdate -format logic -radix hexadecimal tb_full_adder_tri/a     
add wave -noupdate -format logic -radix hexadecimal tb_full_adder_tri/b     
add wave -noupdate -format logic -radix hexadecimal tb_full_adder_tri/c     
      
run 200 ns
