#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog -v ../dut/register.v ../tb/register_tb.v 

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.register_tb -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -color red -radix hexadecimal register_tb/u_register/q     
add wave -noupdate -format logic -color green -radix hexadecimal register_tb/u_register/d     
add wave -noupdate -format logic -radix hexadecimal register_tb/u_register/clk     
add wave -noupdate -format logic -color yellow -radix hexadecimal register_tb/u_register/rst     
      
run 500ns
