#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog -work work ../dut/FPU_ls_lib.v  ../tb/tb_FPU_ls_lib.v 

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.tb_FPU_ls_lib -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -radix hexadecimal tb_FPU_ls_lib/clock     
add wave -noupdate -format logic -radix hexadecimal tb_FPU_ls_lib/reset     
add wave -noupdate -format logic -radix float32 tb_FPU_ls_lib/FP_exponential/io_in_a     
add wave -noupdate -format logic -radix float32 tb_FPU_ls_lib/FP_exponential/io_out_s     
      
run 10 us
