#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog -v ../dut/tim.v ../tb/tb_tim.v 

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.tb_tim -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -radix hexadecimal tb_tim/u_tim/clk     
add wave -noupdate -format logic -radix hexadecimal tb_tim/u_tim/rst     
add wave -noupdate -format logic -radix hexadecimal tb_tim/u_tim/en     
add wave -noupdate -format logic -radix hexadecimal tb_tim/u_tim/nxt_cnt     
add wave -noupdate -format logic -radix hexadecimal tb_tim/u_tim/cnt     
add wave -noupdate -format logic -radix hexadecimal tb_tim/u_tim/nxt_tim     
add wave -noupdate -format logic -radix hexadecimal tb_tim/u_tim/tim     
      
run 5us
