#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog -f ../filelist/filelist.f 

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.tb_simple_dual -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -radix hexadecimal tb_simple_dual/clka     
add wave -noupdate -format logic -radix hexadecimal tb_simple_dual/ena     
add wave -noupdate -format logic -radix hexadecimal tb_simple_dual/wea     
add wave -noupdate -format logic -radix hexadecimal tb_simple_dual/addra     
add wave -noupdate -format logic -radix hexadecimal tb_simple_dual/dina     
add wave -noupdate -format logic -radix hexadecimal tb_simple_dual/clkb     
add wave -noupdate -format logic -radix hexadecimal tb_simple_dual/enb     
add wave -noupdate -format logic -radix hexadecimal tb_simple_dual/addrb     
add wave -noupdate -format logic -radix hexadecimal tb_simple_dual/doutb     
      
run 200ns
