#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
#vlog -v ../dut/full_adder_reg.v ../tb/tb_full_adder_reg.v 
vlog -f ../filelist/filelist.f 

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.tb_full_adder_reg -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -radix hexadecimal tb_full_adder_reg/clk     
add wave -noupdate -format logic -radix hexadecimal tb_full_adder_reg/rst     
add wave -noupdate -format logic -radix hexadecimal tb_full_adder_reg/a     
add wave -noupdate -format logic -radix hexadecimal tb_full_adder_reg/b     
add wave -noupdate -format logic -radix hexadecimal tb_full_adder_reg/c     
add wave -noupdate -format logic -radix hexadecimal tb_full_adder_reg/u_full_adder_reg/sum     
      
run 3us
